quarkus:
  application:
    name:
      high-stack-quarkus

  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: pass

  flyway:
    enabled: true
    schemas: content_creation
    create-schemas: true
    migrate-at-start: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  http:
    root-path: api/
    port: 8081

  log:
    level: INFO
    category:
      "com.yatskevich":
        level: DEBUG

kafka:
  bootstrap:
    servers: kafka:9092
  topic: hs-spring
  groupId: ContentCreation
mp:
  messaging:
    incoming:
      prices:
        connector: smallrye-kafka
